package com.gymandroid.ui.exercise

import android.os.Bundle
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.fragment.app.Fragment
import com.gymandroid.R
import kotlinx.android.synthetic.main.fragment_exercise.view.*


class ExerciseFragment : Fragment() {

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        val root = inflater.inflate(R.layout.fragment_exercise, container, false)
        val isPos = root.findViewById<TextView>(R.id.is_pos)
        Log.d("isPos", isPos.toString())

        // To avoid null pointer exception on is_pos, need to use root.is_pos instead in fragments
        // Synthetic properties generated by Kotlin Android Extensions plugin needs a view for Fragment/Activity to be set before hand.
        // https://stackoverflow.com/a/51674381/12208834
        root.is_pos.text = "hello"
        return root
    }

}
