package com.gymandroid.ui.exercise

import android.os.Bundle
import android.util.Log
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.TextView
import androidx.fragment.app.Fragment
import com.gymandroid.R
import com.gymandroid.ui.exercise.dummy.DummyContent
import kotlinx.android.synthetic.*
import kotlinx.android.synthetic.main.activity_main.*
import kotlinx.android.synthetic.main.fragment_exercise.*
import kotlinx.android.synthetic.main.fragment_exercise.view.*


class ExerciseFragment : Fragment() {

    private lateinit var viewmodel: ExerciseViewModel


    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
//        viewmodel =
//            ViewModelProviders.of(this).get(viewmodel::class.java)
        val root = inflater.inflate(R.layout.fragment_exercise, container, false)
//        val textView: TextView = root.findViewById(R.id.is_pos)
//        viewmodel.text.observe(viewLifecycleOwner, Observer {
//            textView.text = it
//        })
        val isPos = root.findViewById<TextView>(R.id.is_pos)
        Log.d("isPos", isPos.toString())

        // To avoid null pointer exception on is_pos, need to use root.is_pos instead in fragments
        // Synthetic properties generated by Kotlin Android Extensions plugin needs a view for Fragment/Activity to be set before hand.
        // https://stackoverflow.com/a/51674381/12208834
        root.is_pos.text = "hello"
        return root
    }

}
